export const API_URL = {
  LOGIN: '/auth/login',
  SIGN_UP: '/auth/signup',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  REFRESH_TOKEN: '/auth/refresh-token',
  LOGOUT: '/auth/logout',
  USERS: '/users',
  FORMS: '/forms',
  FOLDERS: '/folders',
  INDEPENDENT_FOLDER: '/folders/independent',
  TEAMS: '/teams',
  USER_PROFILE: '/users/my-profile',
  CHANGE_PASSWORD: '/users/change-password',
  UPLOAD_IMAGE: '/upload/image',
  UPLOAD_DOCUMENT: '/upload/document',
  ADD_TO_FOLDER: '/:formId/folder/:folderId/add',
  RESPONSES: '/responses',
  INVITATION: '/invitation',
  TEMPLATES: '/templates',
};
