export const PATH = {
  ROOT_PAGE: '/',
  LOGIN_PAGE: '/login',
  SIGNUP_PAGE: '/signup',
  FORGOT_PASSWORD_PAGE: '/forgot-password',
  RESET_PASSWORD_PAGE: '/reset-password',
  OVERVIEW_PAGE: '/my-forms',
  BUILD_FORM_PAGE: '/build',
  EDIT_FORM_PAGE: '/build/:id',
  MY_ACCOUNT_PAGE: '/my-account',
  PUBLIC_PAGE: '/form/:id',
  RESPONSE_PAGE: '/responses/:formId',
  ACCEPT_INVITATION_PAGE: '/accept-invitation',
  MY_TEAMS_PAGE: '/my-teams/:teamId',
  TEAMS_SETTINGS_PAGE: '/my-teams/:teamId/team-settings',
  TEMPLATES_PAGE: '/templates',
};
