import { ElementItem, ElementType } from '.';

export interface GetFormsParams {
  page?: number;
  pageSize?: number;
  search?: string;
  isDeleted?: number;
  isFavourite?: number;
  sortField?: string;
  sortDirection?: string;
  folderId?: string;
  teamId?: string;
}

export interface FormResponse {
  id: string;
  title: string;
  logoUrl: string;
  settings: object;
  elements: ElementItem[];
  totalSubmissions: number;
  permissions: object;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
  creator: {
    id: string;
    email: string;
    username: string;
  };
  teamId: string;
  folderId: string;
  folder: {
    id: string;
    name: string;
  };
  favouritedByUsers: {
    id: string;
    email: string;
  };
  isFavourite: boolean;
  disabled: boolean;
}

export interface FormDetailsResponse {
  id: string;
  title: string;
  logoUrl: string;
  settings: object;
  disabled: boolean;
  elements: ElementItem[];
  totalSubmissions: number;
  permissions: object;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
  folderId: string;
  teamId: string;
  team: {
    id: string;
    name: string;
    logoUrl: string;
  };
}

export interface GetFormsResponse {
  forms: FormResponse[];
  page: number;
  pageSize: number;
  totalForms: number;
  totalPages: number;
}

export interface FormRequest {
  id?: string;
  disabled?: boolean;
  title: string;
  logoUrl: string;
  settings: object;
  elements: ElementItem[];
  createdAt: string;
  updatedAt: string;
}

export interface ImportFormResponse {
  title: string;
  settings: object;
  elements: {
    type: ElementType;
    gridSize: {
      x: number;
      y: number;
      w: number;
      h: number;
    };
    config: {
      fieldLabel: string;
      required: boolean;
      [key: string]: unknown;
    };
  }[];
}

export interface AutoGeneratedElement {
  type: ElementType;
  config: {
    fieldLabel: string;
    required: boolean;
    [key: string]: unknown;
  };
}
